version: "3.8"

services:
  app:
    build: .
    image: energy-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - mynetwork
    volumes:
      - ./app:/app
    command: ["python", "/app/app.py"]

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: energy-frontend
    ports:
      - "5001:5000"
    depends_on:
      - app
    networks:
      - mynetwork
    volumes:
      - ./frontend:/frontend
    command: ["npx", "serve", "public", "-l", "5000"]
    environment:
      - NODE_ENV=production
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
    driver: local
