# Use official Node.js image
FROM node:17 AS build

# Set the working directory in the container
WORKDIR /frontend

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your frontend files
COPY frontend/ .

# Build the Svelte app
RUN npm run build

# Expose port for serving the app
EXPOSE 5000

# Serve the app
CMD ["npx", "serve", "build", "-l", "5000"]
